spring:
  profiles:
    active: dev # default active profile
  liquibase:
    change-log: classpath:/db/changelog/master.xml
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  http:
    encoding:
      force: true
mybatis:
  configuration:
    cache-enabled: true
    default-statement-timeout: 3000
    map-underscore-to-camel-case: true
  mapper-locations: mapper/*.xml
